# Generated by Django 4.1.1 on 2022-10-02 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_familiar_fecha_nacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='fecha_nacimiento',
            new_name='fecha_creacion',
        ),
    ]
